**PYTHON LIBRARIES:**

**1.Numpy**

Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python. Besides its obvious scientific uses, Numpy can also be used as an efficient multi-dimensional container of generic data.

Key Features of Python NumPy:

**Multidimensional Arrays**: Python NumPy supports arrays with different numbers of dimensions, enabling effective and versatile data management.

**Broadcasting**: NumPy in Python supports broadcasting, a powerful and robust method for executing operations to arrays of various shapes and sizes.

**Integration**: NumPy functions well with other Python scientific computing libraries like SciPy, Matplotib, and Pandas.

**Mathematical Operations**: NumPy offers a variety of math operations, such as linear algebra functions, trigonometric functions, and fundamental arithmetic operations.

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3])
print("Array with Rank 1: \n",arr)

Array with Rank 1: 
 [1 2 3]


In [3]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Array with Rank 2: \n", arr)

Array with Rank 2: 
 [[1 2 3]
 [4 5 6]]


In [4]:
arr = np.array((1, 3, 2))
print("\nArray created using "
      "passed tuple:\n", arr)


Array created using passed tuple:
 [1 3 2]


**2. SciPy**

Scipy is a Python library useful for solving many mathematical equations and algorithms. It is designed on the top of Numpy library that gives more extension of finding scientific mathematical formulae like Matrix Rank, Inverse, polynomial equations, LU Decomposition, etc. Using its high-level functions will significantly reduce the complexity of the code and helps better in analyzing the data.

In [9]:
from scipy.optimize import root
from math import cos


In [10]:
def eqn(x):
  return x + cos(x)

In [11]:
myroot = root(eqn, 0)

In [12]:
print(myroot.x)

[-0.73908513]


R LIBRARIES:

**1.dplyr**

The dplyr package is one of the most powerful and popular package in R. This package was written by the most popular R programmer Hadley Wickham who has written many useful R packages such as ggplot2, tidyr etc.

In [8]:
install.packages("dplyr")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



In [9]:
library(dplyr)


Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union




In [10]:
mydata = read.csv("https://raw.githubusercontent.com/deepanshu88/data/master/sampledata.csv")

In [11]:
sample_n(mydata,3)

Index State      Y2002   Y2003   Y2004   Y2005   Y2006   Y2007   Y2008  
1 C     California 1685349 1675807 1889570 1480280 1735069 1812546 1487315
2 N     New York   1395149 1611371 1170675 1446810 1426941 1463171 1732098
3 M     Missouri   1221316 1858368 1773451 1573967 1374863 1486197 1735099
  Y2009   Y2010   Y2011   Y2012   Y2013   Y2014   Y2015  
1 1663809 1624509 1639670 1921845 1156536 1388461 1644607
2 1426216 1604531 1683687 1500089 1718837 1619033 1367705
3 1800620 1164202 1425363 1800052 1698105 1767835 1996005

In [12]:
x1 = distinct(mydata)

In [13]:
x2 = distinct(mydata, Index, .keep_all= TRUE)

In [14]:
mydata2 = select(mydata, Index, State:Y2008)

**2.tidyr**


tidyr is a data wrangling package in the R programming language that belongs to the larger tidyverse ecosystem. It provides a set of functions for tidying and reshaping datasets, making them more amenable to analysis and visualization. The primary focus of tidyr is on transforming data into a tidy format, as defined by Hadley Wickham's principles of tidy data.

In [15]:
install.packages("tidyverse")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



In [17]:
library(tidyverse)

data <- data.frame(
  ID = c(1, 2, 3),
  Name = c("Alice", "Bob", "Charlie"),
  Test1 = c(85, 90, 78),
  Test2 = c(92, 88, 95)
)

print("Original Data:")
print(data)

data_long <- data %>%
  gather(key = "Test", value = "Score", Test1, Test2)

print("\nReshaped Data:")
print(data_long)


[1] "Original Data:"
  ID    Name Test1 Test2
1  1   Alice    85    92
2  2     Bob    90    88
3  3 Charlie    78    95
[1] "\nReshaped Data:"
  ID    Name  Test Score
1  1   Alice Test1    85
2  2     Bob Test1    90
3  3 Charlie Test1    78
4  1   Alice Test2    92
5  2     Bob Test2    88
6  3 Charlie Test2    95
